services:
  postgres:
    container_name: svc-auth-postgres
    image: postgres:18-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: svc-auth

    volumes:
      - db:/var/lib/postgresql/data

    networks:
      net:
        ipv6_address: fd98:2dd6:8f48:1d99:22e6:f8c8::3
  
  app-dev:
    container_name: svc-auth-app-dev
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - ./src:/app/src:ro
      - ./include:/app/include:ro
      - ./libs:/app/libs:ro
      - ./secrets:/app/secrets:ro
      - ./CMakeLists.txt:/app/CMakeLists.txt:ro
      - ccache_volume:/ccache
    environment:
      CC: ccache clang
      CXX: ccache clang++
      CCACHE_DIR: /ccache
    depends_on:
      - postgres
    cap_add:
      - SYS_ADMIN

    networks:
      net:
        ipv6_address: fd98:2dd6:8f48:1d99:22e6:f8c8::2

networks:
  net:
    enable_ipv6: true
    enable_ipv4: false
    driver_opts:
      com.docker.network.driver.mtu: "65535"
    ipam:
      config:
        - subnet: fd98:2dd6:8f48:1d99:22e6:f8c8::/96
  host_bridge:
    external: true
    name: bridge

volumes:
  db:
  ccache_volume:
