services:
  app-dev:
    container_name: svc-auth-app-dev
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - ./src:/app/src:ro
      - ./include:/app/include:ro
      - ./libs:/app/libs:ro
      - ./secrets:/app/secrets:ro
      - ./CMakeLists.txt:/app/CMakeLists.txt:ro
      - ccache_volume:/ccache
    environment:
      CC: ccache clang
      CXX: ccache clang++
      CCACHE_DIR: /ccache
      USER_SERVICE_URL: "https://elysium-services.mcbeeland.ru:443"
      DOX_SERVICE_URL: "https://elysium-services.mcbeeland.ru:443"
    depends_on:
      - postgres
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    networks:
      shared-net:
        ipv6_address: fd98:2dd6:8f48:1d99:22e6:f8c8::2

  postgres:
    container_name: svc-auth-postgres
    image: postgres:18-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: svc-auth

    volumes:
      - db:/var/lib/postgresql

    networks:
      shared-net:
        ipv6_address: fd98:2dd6:8f48:1d99:22e6:f8c8::3

networks:
  shared-net:
    external: true
    name: svc-net

volumes:
  db:
  ccache_volume:
